branches:
  only:
  - master
dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
 - pip install -r requirements.txt
script:
 - cd decide
# - python ./manage.py test voting --keepdb

deploy:
  skip_cleanup: true
  provider: heroku
  app: decide-zapdos-votacion
  strategy: git
  api_key:
    secure: dQuNuFCf6/z1tOOI9bL8a8Xj3IMA1nWEehWMKLjbLtyf7h5OrL1MLNqXdphfCoaqdQPfnYLrpozA7dsapV2pVCOaKNk1ULb8juIykF+cIhGRgpACefc55H6cfa3mIVoD4kMydVkAd1SJcJYs6eFWOUiYp7DjIvcVLRgcxtoPx/mqLzRdwjqegslgWsOlovxWg1c1cQYMGAsLozUrg/ge0IVTijL0BeHLCFMDV8pEmSEEB23JFl5urIgTR7+oKYOereZ3f82uPXw+qpF2XO3e8VcqrhkjGv9+KfrRa6qPfaUIBdHmgwby/cdlO70w1tMFt9A53/SQ1wGucAJwGs1D7cDTAKDkLpAxi8UlTt+5RI4xRIUlSUFNSUxhb5EVGgO+sg4QyDVctzcYOP1pZhigUZ0u9gUwIDvjLtkgb/+H7fumTvGK67iTqA6AiHHx8PRhldoMK/E7M4XLe4CROer2Mit9maYu9bIekTlz45jlsUzJCZVOQnQ2jm3PsinNSRnaQUHpwIwjm0nbgHp6MXAUUL/2kp88xfYP2l5O15WTp9oDj20Wasge78dafGzS9bWQm3JBAqZbpkBPhmjq5SzaSmSHB0jbU5YbTa7fjCs8Zf3pocitSRRVBED4KuRxjKWG7GF5+Q3S7a5uO4ckRIM5oiE93bF5tNvK+QzrOPwWsu8=
