# Generated by Django 3.0.2 on 2020-01-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='with_weight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
