# Generated by Django 3.0.2 on 2020-01-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20200103_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='with_weight',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='weight',
        ),
    ]
