# Generated by Django 3.0.2 on 2020-01-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20200103_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='with_weight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
